/** @format */
export const Info = [
  {
    id: 1,
    data: [
      "Purchase the new cylinder lock.",
      "Gather tolis: Screwdriver, pliers (optional), lubricant (optional).",
      "Prepare the area.",
      "Remove the lid cylinder lock.",
      "Insert the new cylinder lock.",
      "Test the new lock.",
      "Lubricate if necessary.",
      "Reassemble any components.",
      "Dispose of the lid lock if needed.",
      "Keep spare keys (optional).",
    ],
    video: "https://www.youtube.com/embed/BEB_8VphSUY",
  },
  {
    id: 2,
    data: [
      "Purchase the New Lock Body.",
      "Gather Tools: Screwdriver, pliers, tape measure, lubricant (optional).",
      "Prepare the Area.",
      "Remove the Old Door Lock Body.",
      "Install the New Lock Body.",
      "Test the New Lock.",
      "Lubricate if Necessary.",
      "Reassemble Any Components.",
      "Dispose of the Old Lock Body if Needed.",
      "Keep Spare Keys (optional).",
    ],
    video: "https://www.youtube.com/embed/TFR-FfTJPZk",
  },
  {
    id: 3,
    data: [
      "Turn Off the Power.",
      "Gather Tools: Ladder (if needed), clean cloth or gloves.",
      "Remove the Old Fluorescent Tube.",
      "Install the New Fluorescent Tube.",
      "Turn On the Power.",
      "Dispose of the Old Tube Properly.",
    ],
    video: "https://www.youtube.com/embed/M0CAnQgEPZw",
  },
  {
    id: 4,
    data: [
      "Turn Off the Power.",
      "Gather Tools: Ladder (if needed), clean cloth or gloves.",
      "Remove the Fluorescent Tube (if necessary).",
      "Locate and Remove the Old Starter.",
      "Install the New Starter.",
      "Reinstall the Fluorescent Tube (if removed).",
      "Turn On the Power",
      "Test the Light.",
    ],
    video: "https://www.youtube.com/embed/K3wu2r1RWpA",
  },
  {
    id: 5,
    data: [
      " Turn Off the Power: Switch off the circuit breaker.",
      "Test for Power: Confirm the outlet is dead using a voltage tester.",
      " Remove Cover Plate: Unscrew and remove the plate.",
      "Unscrew and Remove Outlet: Unscrew the outlet and pull it out.",
      "Disconnect Wires: Note wire positions (black, white, ground) and disconnect them.",
      "      Prepare Wires: Strip insulation if necessary.",

      "   Install New Outlet: Secure the outlet to the box.",
      "Attach Cover Plate: Screw the cover plate back on.",
      "Restore Power: Turn the circuit breaker back on.",
      "Test New Outlet: Confirm functionality with a voltage tester and by plugging in a device",
    ],
    video: "https://www.youtube.com/embed/WC7F-Ag9fXQ",
  },
];
