/** @format */
export const Info = [
  {
    id: 1,
    data: [
      "Purchase the new cylinder lock.",
      "Gather tolis: Screwdriver, pliers (optional), lubricant (optional).",
      "Prepare the area.",
      "Remove the lid cylinder lock.",
      "Insert the new cylinder lock.",
      "Test the new lock.",
      "Lubricate if necessary.",
      "Reassemble any components.",
      "Dispose of the lid lock if needed.",
      "Keep spare keys (optional).",
    ],
    video: "https://www.youtube.com/embed/BEB_8VphSUY",
  },
  {
    id: 2,
    data: [
      "fgrdck.",
      "Gather tolis: Screwdriver, pliers (optional), lubricant (optional).",
      "Prepare the area.",
      "Remove the lid cylinder lock.",
      "Insert the new cylinder lock.",
      "Test the new lock.",
      "Lubricate if necessary.",
      "Reassemble any components.",
      "Dispose of the lid lock if needed.",
      "Keep spare keys (optional).",
    ],
    video: "https://www.youtube.com/embed/TFR-FfTJPZk",
  },
  {
    id: 3,
    data: [
      "Purchase the new cylinder lock.",
      "Gather tolis: Screwdriver, pliers (optional), lubricant (optional).",
      "Prepare the area.",
      "Remove the lid cylinder lock.",
      "Insert the new cylinder lock.",
      "Test the new lock.",
      "Lubricate if necessary.",
      "Reassemble any components.",
      "Dispose of the lid lock if needed.",
      "Keep spare keys (optional).",
    ],
    video: "https://www.youtube.com/embed/M0CAnQgEPZw",
  },
  {
    id: 4,
    data: [
      "Purchase the new cylinder lock.",
      "Gather tolis: Screwdriver, pliers (optional), lubricant (optional).",
      "Prepare the area.",
      "Remove the lid cylinder lock.",
      "Insert the new cylinder lock.",
      "Test the new lock.",
      "Lubricate if necessary.",
      "Reassemble any components.",
      "Dispose of the lid lock if needed.",
      "Keep spare keys (optional).",
    ],
    video: "https://www.youtube.com/embed/K3wu2r1RWpA",
  },
];
